Clarifying language in the readme, in particular for `link` vs. `cause`
mike-kaufman/async-context-definition pull request #17
Opened 2018-03-29 18:19 UTC by daanx

2018-04-02 15:03 UTC, mike-kaufman requested changes
Thanks Daan, lmk if you want to talk f2f on terminology choices.

2018-04-02 15:03 UTC, mike-kaufman commented on README.md
> +3.  `cause` - indicates a previously linked callback was "resolved" and is now enabled for execution.
I think `resolved` is going to cause confusion with resolved promises.  In this case, `"cause"` means the preceding promise in the promise chain was resolved, and this current function is free to  proceed.

2018-04-02 15:03 UTC, mike-kaufman commented on README.md
> +{"event": "cause", "executeID":0, "linkID": 1, "causeID": 2}  // indicates f1() is "resolved" and queued for execution (in the timeout queue)
Again, replace "resolved" w/ "readied"?  Or... ??? Open to suggestions here.

2018-04-16 18:51 UTC, daanx commented on README.md
> +3.  `cause` - indicates a previously linked callback was "resolved" and is now enabled for execution.
I agree. Perhaps we should rephrase referring to a task being completed, something like:

2. `link` - indicates a callback was registered for later asynchronous execution when a task is completed.

3. `cause` - indicates a task was completed and the callback linked to that task is now enabled for execution.

Does that sound good? And perhaps we should thus rename `cause` to `ready` ?

2018-04-16 18:53 UTC, daanx commented on README.md
> +{"event": "cause", "executeID":0, "linkID": 1, "causeID": 2}  // indicates f1() is "resolved" and queued for execution (in the timeout queue)
So, here it becomes `indicates the (timeout) task is complete and `f1` is now ready for execution`.

2025-05-29 19:26 UTC, closed without merging